package com.springAWS.demo.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.util.Objects;



@DynamoDBTable(tableName = "user_profile_image_DB")
public class UserProfile implements Serializable {

    @DynamoDBHashKey(attributeName = "userProfileId")
    @DynamoDBAutoGeneratedKey
    private String userProfileId;
    @DynamoDBAttribute
    private String userName;
    @DynamoDBAttribute
    private String userProfileImageLink = ""; // S3 key

    public UserProfile(){}
    public UserProfile(String userProfileId, String userName, String userProfileImageLink) {
        this.userProfileId = userProfileId;
        this.userName = userName;
        this.userProfileImageLink = userProfileImageLink;
    }

    public String getUserProfileId() {
        return userProfileId;
    }

    public void setUserProfileId(String userProfileId) {
        this.userProfileId = userProfileId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserProfileImageLink() {
        return userProfileImageLink;
    }

    public void setUserProfileImageLink(String userProfileImageLink) {
        this.userProfileImageLink = userProfileImageLink;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserProfile that)) return false;
        return Objects.equals(getUserProfileId(), that.getUserProfileId()) &&
                Objects.equals(getUserName(), that.getUserName()) &&
                Objects.equals(getUserProfileImageLink(), that.getUserProfileImageLink());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUserProfileId(), getUserName(), getUserProfileImageLink());
    }
}
